{% set version = "0.1.1" %}

package:
    name: conda-exec
    version: {{ version }}

build:
    number: 0
    skip: True  # [win]
    script:
        - install ${RECIPE_DIR}/conda-exec.sh ${PREFIX}/bin/conda-exec

requirements:
    run:
        - conda

test:
    commands:
        - conda exec -h

about:
    home: https://github.com/nomr/conda-exec
    license: BSD 3-Clause
    license_family: BSD
    license_file: ${RECIPE_DIR}/LICENSE
    summary: Executes a command inside a conda environment

    dev_url: https://github.com/nomr/conda-exec

extra:
    recipe-maintainers:
        - sodre
